### ISSUE TITLE
Timezone information error on Windows

### ISSUE THREAD

**Issue by jskiba99** [thomaspatzke/WASE#10]
When running under jython, it appears unix.py recognizes the system as non-win32 and as such tries to look for timezone information in unix locations. I copied a \etc\localtime file from a linux machine to C:\etc\localtime and that seems to work ok. I'm not sure if or where this would be fixed but it might be worth noting in the extension docs for those trying the extension on windows.  It was the first error I ran into and prevented the extension from loading.

Traceback (most recent call last):
  File "C:\Users\user1\AppData\Roaming\BurpSuite\bapps\67f5c31f93d04ad3a3b0a1808b3648fa\ElasticBurp.py", line 22, in <module>
    from doc_HttpRequestResponse import DocHTTPRequestResponse
  File "C:\Users\user1\AppData\Roaming\BurpSuite\bapps\67f5c31f93d04ad3a3b0a1808b3648fa\doc_HttpRequestResponse.py", line 26, in <module>
    tz = get_localzone()
  File "C:\Users\user1\AppData\Roaming\BurpSuite\bapps\67f5c31f93d04ad3a3b0a1808b3648fa\BappModules\tzlocal\unix.py", line 123, in get_localzone
    _cache_tz = _get_localzone()
  File "C:\Users\user1\AppData\Roaming\BurpSuite\bapps\67f5c31f93d04ad3a3b0a1808b3648fa\BappModules\tzlocal\unix.py", line 117, in _get_localzone
    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'

    at org.python.core.PyException.doRaise(PyException.java:226)

**Comment by thomaspatzke** [comment]
I think dfbd44afb16bc3e6bc43bc55433defc615161223 fixes it - unfortunately not able to verify the fix because I'm stuck at some elasticsearch_dsl errors. Can you try it again with the latest version from this repository?

**Comment by jskiba99** [comment]
That fixed that one. There is one other instance here.

https://github.com/thomaspatzke/WASE/blob/233bc92ea558d4ab688bc65f70c77460ebfbce63/ElasticBurp.py#L29

**Comment by thomaspatzke** [comment]
Thanks for contribution!
